# -*- coding: utf-8 -*-
"""Lab_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VgJiwKlNn23YPwzebCLqBawKVsbtSMjF
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

data = pd.read_csv("spambase.data", header=None)
X = data.iloc[:, :-1].values   # 57 features
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# y = le.fit_transform(y)- Alphabrtic order happens..
# print(le.classes_)
# y = y.replace({"negative": 0, "positive": 1})
y = data.iloc[:, -1].values.reshape(-1, 1)  # labels

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
# X_scaled = np.c_[np.ones((X_scaled.shape[0], 1)), X_scaled]
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42 #x_scaled,...
)
X_train = np.c_[np.ones((X_train.shape[0], 1)), X_train]
X_test  = np.c_[np.ones((X_test.shape[0], 1)), X_test]

X_train_main, X_val, y_train_main, y_val = train_test_split(
    X_train, y_train, test_size=0.2, random_state=42
)

def sigmoid(z):
    z = np.clip(z, -500, 500) # to avoid over-range values.
    return 1 / (1 + np.exp(-z))

def compute_loss(y, y_hat):
    eps = 1e-9
    return -np.mean(y * np.log(y_hat + eps) + (1 - y) * np.log(1 - y_hat + eps))

def logistic_gd(X, y, lr=0.001, epochs=1000):
    m, n = X.shape
    y = y.reshape(-1, 1) # No needed, we done before above: but not harm any..
    # add bias column using np.c_
    # X = np.c_[np.ones((m, 1)), X]   # shape: (m, n+1)
    w = np.zeros((n, 1))
    losses = []
    for _ in range(epochs):
        z = np.dot(X, w)
        y_hat = sigmoid(z)
        dw = (1/m) * np.dot(X.T, (y_hat - y))
        w -= lr * dw
        losses.append(compute_loss(y, y_hat))

    return w, losses

def logistic_sgd(X, y, lr=0.01, epochs=10):
    m, n = X.shape
    y = y.reshape(-1, 1)
    # add bias column
    # X = np.c_[np.ones((m, 1)), X]   # (m, n+1)
    w = np.zeros((n, 1))
    losses = []
    for _ in range(epochs):
        for i in range(m):
            xi = X[i].reshape(1, -1)   # (1, n+1)
            yi = y[i]                  # (1,)
            y_hat = sigmoid(np.dot(xi, w))  # (1,1)
            dw = xi.T * (y_hat - yi)
            w -= lr * dw
        losses.append(compute_loss(y, sigmoid(np.dot(X, w))))

    return w, losses

def predict(X, w, threshold=0.5):
    m = X.shape[0]
    # add bias column
    # X = np.c_[np.ones((m, 1)), X]
    probs = sigmoid(np.dot(X, w))
    return (probs >= threshold).astype(int)

w_gd,loss_gd = logistic_gd(X_train_main, y_train_main)
w_sgd,loss_sgd = logistic_sgd(X_train_main, y_train_main)

plt.plot(loss_gd, label="Gradient Descent")
# plt.plot(loss_sgd, label="Stochastic GD")
plt.xlabel("Iterations")
plt.ylabel("Loss")
plt.legend()
plt.show()

def evaluate(y_true, y_pred):
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1-score": f1_score(y_true, y_pred),
        "Confusion Matrix": confusion_matrix(y_true, y_pred)
    }

print("GD – Train:", evaluate(y_train_main, predict(X_train_main, w_gd)))
print("GD – Test:", evaluate(y_test, predict(X_test, w_gd)))

print("\nSGD – Train:", evaluate(y_train_main, predict(X_train_main, w_sgd)))
print("SGD – Test:", evaluate(y_test, predict(X_test, w_sgd)))

def logistic_gd_l2(X, y, lr=0.01, epochs=1000, lam=0.1):
    m, n = X.shape
    y = y.reshape(-1, 1)
    w = np.zeros((n, 1))
    losses = []
    for _ in range(epochs):
        y_hat = sigmoid(np.dot(X, w))
        # L2: do NOT regularize bias term (w[0])
        dw = (1/m) * np.dot(X.T, (y_hat - y))
        dw[1:] += (lam / m) * w[1:]
        w -= lr * dw
        loss = compute_loss(y, y_hat) + (lam / (2*m)) * np.sum(w[1:]**2)
        losses.append(loss)

    return w, losses

lambdas = [0, 0.001, 0.01, 0.1, 1]
best_lambda = None
best_acc = 0
for lam in lambdas:
    w, losses = logistic_gd_l2(X_train_main, y_train_main, lam=lam)
    val_pred = predict(X_val, w)
    acc = accuracy_score(y_val, val_pred)
    if acc > best_acc:
        best_acc = acc
        best_lambda = lam

print("Best Lambda:", best_lambda)

w_l2,loss_l2 = logistic_gd_l2(X_train, y_train, lam=best_lambda)

m, n = X_train.shape   # n = 58 (1 bias + 57 features)
for i in range(1, n):  # skip bias at index 0
        x_vals = X_train[:, i]
        # scatter actual data
        plt.scatter(x_vals, y_train, alpha=0.3, label="Data")
        # logistic regression curve for this feature
        x_line = np.linspace(x_vals.min(), x_vals.max(), 300)
        y_line = sigmoid(w[0] + w[i] * x_line)
        plt.plot(x_line, y_line, color="red", label="Logistic curve")
        plt.xlabel(f"Feature {i}")
        plt.ylabel("Probability / Class")
        plt.title(f"Logistic Regression for Feature {i}")
        plt.legend()
        plt.show()

# # kaggle_data = pd.read_csv("spam_ham_dataset.csv")
# # emails = kaggle_data.iloc[:5, 1]
# # # (Assume feature extraction already done)
# # # Placeholder prediction example:
# # print("Predicted classes:", predict(X_test[:5], w_l2).flatten())
# data = pd.read_csv("spam_ham_dataset.csv")

# X_text = data["text"].values        # email text
# y = data["label"].values.reshape(-1, 1)  # 0 = ham, 1 = spam

# # -----------------------------
# # 2. Feature extraction (TF-IDF)
# # -----------------------------
# vectorizer = TfidfVectorizer(stop_words="english", max_features=3000)
# X = vectorizer.fit_transform(X_text).toarray()

# # add bias column
# X = np.c_[np.ones((X.shape[0], 1)), X]

# # -----------------------------
# # 3. Train-test split
# # -----------------------------
# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )

# # -----------------------------
# # 4. Train your Logistic Regression (GD)
# # -----------------------------
# def sigmoid(z):
#     z = np.clip(z, -500, 500)
#     return 1 / (1 + np.exp(-z))

# def compute_loss(y, y_hat):
#     eps = 1e-9
#     return -np.mean(y*np.log(y_hat+eps) + (1-y)*np.log(1-y_hat+eps))

# def logistic_gd(X, y, lr=0.01, epochs=500):
#     m, n = X.shape
#     w = np.zeros((n, 1))
#     for _ in range(epochs):
#         y_hat = sigmoid(np.dot(X, w))
#         dw = (1/m) * np.dot(X.T, (y_hat - y))
#         w -= lr * dw
#     return w

# def predict(X, w, threshold=0.5):
#     probs = sigmoid(np.dot(X, w))
#     return (probs >= threshold).astype(int)

# w = logistic_gd(X_train, y_train)

# # -----------------------------
# # 5. Predict ANY 5 emails
# # -----------------------------
# emails_5 = data.iloc[:5]["text"].values

# X_5 = vectorizer.transform(emails_5).toarray()
# X_5 = np.c_[np.ones((X_5.shape[0], 1)), X_5]

# preds = predict(X_5, w)

# # -----------------------------
# # 6. Print results
# # -----------------------------
# for i in range(5):
#     print(f"\nEmail {i+1}:")
#     print("Predicted class:", "SPAM" if preds[i][0] == 1 else "HAM")

# x_manual = np.array([0.25.0.1,..])
# x_manual = np.c_[np.ones((1, 1)), x_manual]   # shape (1, 58)
# prob = sigmoid(np.dot(x_manual, w_l2))
# label = (prob >= 0.5).astype(int)

# print("Probability:", prob[0][0])
# print("Predicted label:", label[0][0])
# # from sklearn.linear_model import LogisticRegression
# model = LogisticRegression(
#     max_iter=1000,     # ensure convergence
#     solver="lbfgs"     # default, good for binary classification
# )

# # -------------------------------------------------
# # 5. Train Model
# # -------------------------------------------------
# model.fit(X_train, y_train)
# y_train_pred = model.predict(X_train)
# y_test_pred = model.predict(X_test)
# sample = X_test[0].reshape(1, -1)
# prob = model.predict_proba(sample)[0][1]
# pred = model.predict(sample)[0]
# -- true vs predicted......
# y_test_pred = predict(X_test, w_gd)   # or w_sgd
# print("True Label  |  Predicted Label")
# print("-------------------------------")
# for i in range(len(y_test)):
#     print(f"{y_test[i][0]}           |  {y_test_pred[i][0]}")