# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgGgJsHzzWRU8OviYza7rFEGQ4vfVJtG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import LabelEncoder
from collections import Counter
from sklearn.model_selection import train_test_split
from itertools import combinations

# def discretize_column(col, bins=3):
#     min_val = col.min()
#     max_val = col.max()
#     width = (max_val - min_val) / bins

#     def assign_bin(x):
#         for i in range(bins):
#             if x <= min_val + width * (i + 1):
#                 return i
#         return bins - 1

#     return col.apply(assign_bin)
# for col in X.columns:
#     X[col] = discretize_column(X[col], bins=3)

# data = pd.concat([X, y], axis=1)
# data.head()
# ==============================
# Load Iris dataset (UCI)
# ==============================
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
cols = ["sl", "sw", "pl", "pw", "class"]

dataset = pd.read_csv(url, header=None, names=cols)
dataset.dropna(inplace=True)

# ==============================
# Encode class labels manually
# ==============================
class_map = {
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
}
dataset["class"] = dataset["class"].map(class_map)

# ==============================
# Discretization (PERCENTILE / QUANTILE based)
# ==============================
def discretize_column(col, bins=3):
    # percentile cut points
    thresholds = np.percentile(col, [100/bins * i for i in range(1, bins)])
    return np.digitize(col, thresholds)

for column in dataset.columns[:-1]:
    dataset[column] = discretize_column(dataset[column], bins=3)

# ==============================
# Split features and labels
# ==============================
X = dataset.iloc[:, :-1].values
y = dataset["class"].values

# ==============================
# Train–test split (recommended)
# ==============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=123, stratify=y
)
# %%
class Node:
    def __init__(self, feature=None, threshold=None, info_gain=None, left=None, right=None, value=None):

        # Decision node attributes
        self.feature = feature
        self.threshold = threshold
        self.info_gain = info_gain
        self.left = left
        self.right = right

        # Leaf node attribute
        self.value = value

# %%
class DecisionTree:
    def __init__(self, min_samples=2, max_depth=2):
        self.min_samples = min_samples
        self.max_depth = max_depth

    def build_tree(self, dataset, curr_depth=0):
        X = dataset[:, :-1]
        y = dataset[:, -1]
        n_samples, n_features = X.shape

        if n_samples >= self.min_samples and curr_depth <= self.max_depth:
            best_split = self.best_split(dataset, n_features)

            if best_split["info_gain"] > 0:
                left_node = self.build_tree(
                    best_split["left_dataset"], curr_depth+1)
                right_node = self.build_tree(
                    best_split["right_dataset"], curr_depth+1)

                return Node(best_split["feature"], best_split["threshold"], best_split["info_gain"], left_node, right_node)
        leaf_value = Counter(y).most_common(1)[0][0]
        return Node(value=leaf_value)

    def best_split(self, dataset, n_features):
        best_split = {'feature': None, 'threshold': None,
                      'info_gain': -1, 'left_dataset': None, 'right_dataset': None}

        for feature in range(n_features):
            feature_values = dataset[:, feature]
            thresholds = np.unique(feature_values)

            for threshold in thresholds:
                left_dataset, right_dataset = self.split(
                    dataset, feature, threshold)

                if len(left_dataset) and len(right_dataset):
                    parent_y, left_y, right_y = dataset[:, -
                                                        1], left_dataset[:, -1], right_dataset[:, -1]
                    info_gain = self.information_gain(
                        parent_y, left_y, right_y)

                    if info_gain > best_split['info_gain']:
                        best_split['feature'] = feature
                        best_split['threshold'] = threshold
                        best_split['info_gain'] = info_gain
                        best_split['left_dataset'] = left_dataset
                        best_split['right_dataset'] = right_dataset
        return best_split

    def split(self, dataset, feature, threshold):
        left_dataset = np.array(
            [row for row in dataset if row[feature] <= threshold])
        right_dataset = np.array(
            [row for row in dataset if row[feature] > threshold])

        return left_dataset, right_dataset

    def information_gain(self, parent_y, left_y, right_y):
        left_weight = len(left_y) / len(parent_y)
        right_weight = len(right_y) / len(parent_y)

        information_gain = self.entropy(
            parent_y) - (left_weight * self.entropy(left_y) + right_weight * self.entropy(right_y))
        return information_gain

    def entropy(self, y):
        entropy = 0
        class_labels = np.unique(y)
        for class_label in class_labels:
            p = len(y[y == class_label]) / len(y)
            entropy += -p * np.log2(p)

        return entropy

    def fit(self, X, y):
        dataset = np.concatenate([X, y.reshape(-1, 1)], axis=1)
        self.root = self.build_tree(dataset)

    # def predict(self, x):
    #     predictions = [self.predict_class(row, self.root) for row in x]
    #     return predictions
    def predict(self, x):
        predictions = []
        for row in x:
            pred = self.predict_class(row, self.root)
            predictions.append(pred)
        return predictions


    def predict_class(self, row, node):
        if node.value != None:
            return node.value

        feature = row[node.feature]
        if feature <= node.threshold:
            return self.predict_class(row, node.left)
        else:
            return self.predict_class(row, node.right)

    def print_tree(self, node=None, depth=0, indent="|    "):
        prefix = indent * depth
        if node is None:
            node = self.root

        if node.value is not None:
            print(f"{prefix}|--- Class: {node.value}")
            return
        feature_label = f"feature {node.feature}"
        print(
            f"{prefix}|--- {feature_label} <= {node.threshold}, Info Gain={node.info_gain:.4f}")
        self.print_tree(node.left, depth + 1, indent)

        print(
            f"{prefix}|--- {feature_label} > {node.threshold}, Info Gain={node.info_gain:.4f}")
        self.print_tree(node.right, depth + 1, indent)

# %%


class DecisionTree_pruning:
    def __init__(self, min_samples=2, max_depth=2, error_threshold=0.01):
        self.min_samples = min_samples
        self.max_depth = max_depth
        self.error_threshold = error_threshold

    def build_tree(self, dataset, curr_depth=0):
        X = dataset[:, :-1]
        y = dataset[:, -1]
        n_samples, n_features = X.shape

        if n_samples >= self.min_samples and curr_depth <= self.max_depth:
            best_split = self.best_split(dataset, n_features)
            parent_error = self.classification_error(y)

            if best_split["info_gain"] > 0:
                left_y = best_split["left_dataset"][:, -1]
                right_y = best_split["right_dataset"][:, -1]

                left_error = self.classification_error(left_y)
                right_error = self.classification_error(right_y)

                weighted_error = (
                    len(left_y)/len(y) * left_error +
                    len(right_y)/len(y) * right_error
                )

                error_reduction = parent_error - weighted_error

                if error_reduction >= self.error_threshold:
                    left_node = self.build_tree(
                        best_split["left_dataset"], curr_depth + 1)
                    right_node = self.build_tree(
                        best_split["right_dataset"], curr_depth + 1)
                    return Node(best_split["feature"], best_split["threshold"], best_split["info_gain"], left_node, right_node)
        leaf_value = Counter(y).most_common(1)[0][0]
        return Node(value=leaf_value)

    def best_split(self, dataset, n_features):
        best_split = {'feature': None, 'threshold': None,
                      'info_gain': -1, 'left_dataset': None, 'right_dataset': None}

        for feature in range(n_features):
            feature_values = dataset[:, feature]
            thresholds = np.unique(feature_values)

            for threshold in thresholds:
                left_dataset, right_dataset = self.split(
                    dataset, feature, threshold)

                if len(left_dataset) and len(right_dataset):
                    parent_y, left_y, right_y = dataset[:, -
                                                        1], left_dataset[:, -1], right_dataset[:, -1]
                    info_gain = self.information_gain(
                        parent_y, left_y, right_y)

                    if info_gain > best_split['info_gain']:
                        best_split['feature'] = feature
                        best_split['threshold'] = threshold
                        best_split['info_gain'] = info_gain
                        best_split['left_dataset'] = left_dataset
                        best_split['right_dataset'] = right_dataset
        return best_split

    def split(self, dataset, feature, threshold):
        left_dataset = np.array(
            [row for row in dataset if row[feature] <= threshold])
        right_dataset = np.array(
            [row for row in dataset if row[feature] > threshold])

        return left_dataset, right_dataset

    def information_gain(self, parent_y, left_y, right_y):
        left_weight = len(left_y) / len(parent_y)
        right_weight = len(right_y) / len(parent_y)

        information_gain = self.entropy(
            parent_y) - (left_weight * self.entropy(left_y) + right_weight * self.entropy(right_y))
        return information_gain

    def entropy(self, y):
        entropy = 0
        class_labels = np.unique(y)
        for class_label in class_labels:
            p = len(y[y == class_label]) / len(y)
            entropy += -p * np.log2(p)

        return entropy

    def classification_error(self, y):
        counts = Counter(y)
        max_count = max(counts.values())
        return 1 - (max_count / len(y))

    def fit(self, X, y):
        dataset = np.concatenate([X, y.reshape(-1, 1)], axis=1)
        self.root = self.build_tree(dataset)

    def predict(self, x):
        predictions = [self.predict_class(row, self.root) for row in x]
        return predictions

    def predict_class(self, row, node):
        if node.value != None:
            return node.value

        feature = row[node.feature]
        if feature <= node.threshold:
            return self.predict_class(row, node.left)
        else:
            return self.predict_class(row, node.right)

    def print_tree(self, node=None, depth=0, indent="|    "):
        prefix = indent * depth
        if node is None:
            node = self.root

        if node.value is not None:
            print(f"{prefix}|--- Class: {node.value}")
            return
        feature_label = f"feature {node.feature}"
        print(
            f"{prefix}|--- {feature_label} <= {node.threshold}, Info Gain={node.info_gain:.4f}")
        self.print_tree(node.left, depth + 1, indent)

        print(
            f"{prefix}|--- {feature_label} > {node.threshold}, Info Gain={node.info_gain:.4f}")
        self.print_tree(node.right, depth + 1, indent)


# %%
model = DecisionTree(min_samples=5, max_depth=2)
model.fit(X_train, y_train)
predictions = model.predict(X_test)

# %%
accuracy = np.mean(predictions == y_test) * 100
print(f"Accuracy: {accuracy:.2f}%")

# %%
model2 = DecisionTree_pruning(
    min_samples=2, max_depth=2, error_threshold=0.0001)
model2.fit(X_train, y_train)
predictions = model2.predict(X_test)

# %%
accuracy = np.mean(predictions == y_test) * 100
print(f"Accuracy: {accuracy:.2f}%")

# %%
model.print_tree()

# %%
model2.print_tree()

# %%


def plot_decision_boundary(X, y, model, feature_idx, feature_names):
    X_pair = X[:, feature_idx]

    model.fit(X_pair, y)

    x_min, x_max = X_pair[:, 0].min() - 1, X_pair[:, 0].max() + 1
    y_min, y_max = X_pair[:, 1].min() - 1, X_pair[:, 1].max() + 1

    xx, yy = np.meshgrid(
        np.linspace(x_min, x_max, 300),
        np.linspace(y_min, y_max, 300)
    )

    Z = np.array(model.predict(np.c_[xx.ravel(), yy.ravel()]))
    Z = Z.reshape(xx.shape)

    plt.contourf(xx, yy, Z, alpha=0.4)
    plt.scatter(X_pair[:, 0], X_pair[:, 1], c=y, edgecolors="k")
    plt.xlabel(feature_names[feature_idx[0]])
    plt.ylabel(feature_names[feature_idx[1]])


def plot_all_feature_pairs(X, y, model):
    feature_names = ["sepal_length", "sepal_width",
                     "petal_length", "petal_width"]
    pairs = list(combinations(range(X.shape[1]), 2))

    plt.figure(figsize=(15, 10))

    for i, pair in enumerate(pairs):
        plt.subplot(2, (len(pairs)+1)//2, i+1)
        plot_decision_boundary(X, y, model, pair, feature_names)
        plt.title(f"{feature_names[pair[0]]} vs {feature_names[pair[1]]}")

    plt.tight_layout()
    plt.show()


# %%
plot_all_feature_pairs(X, y, model)

# %%


class RandomForest:
    def __init__(self, n_trees=10, max_depth=5, min_samples=2, max_features=None):
        self.n_trees = n_trees
        self.max_depth = max_depth
        self.min_samples = min_samples
        self.max_features = max_features
        self.trees = []

    def bootstrap_sample(self, X, y):
        n_samples = X.shape[0]
        idxs = np.random.choice(n_samples, n_samples, replace=True)
        return X[idxs], y[idxs]

    def fit(self, X, y):
        self.trees = []

        for _ in range(self.n_trees):
            X_sample, y_sample = self.bootstrap_sample(X, y)

            if self.max_features:
                feature_idxs = np.random.choice(
                    X.shape[1], self.max_features, replace=False
                )
            else:
                feature_idxs = np.arange(X.shape[1])

            tree = DecisionTree(
                max_depth=self.max_depth,
                min_samples=self.min_samples
            )

            tree.fit(X_sample[:, feature_idxs], y_sample)
            self.trees.append((tree, feature_idxs))

    def predict(self, X):
        tree_preds = []

        for tree, feature_idxs in self.trees:
            preds = tree.predict(X[:, feature_idxs])
            tree_preds.append(preds)

        tree_preds = np.array(tree_preds).T

        return [Counter(row).most_common(1)[0][0] for row in tree_preds]


# %%
rf = RandomForest(
    n_trees=20,
    max_depth=5,
    max_features=int(np.sqrt(X_train.shape[1]))  # standard RF rule
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# %%
rf_horizontal = RandomForest(
    n_trees=20,
    max_depth=5,
    max_features=None   # all features
)
rf_horizontal.fit(X_train, y_train)

# %%
rf_vertical = RandomForest(
    n_trees=20,
    max_depth=5,
    max_features=2   # random features per tree
)
rf_vertical.fit(X_train, y_train)

# %%
rf_both = RandomForest(
    n_trees=20,
    max_depth=5,
    max_features=int(np.sqrt(X_train.shape[1]))
)
rf_both.fit(X_train, y_train)

# %%


def evaluate(y_true, y_pred, title):
    print("=" * 60)
    print(title)
    print("=" * 60)

    print("Classification Report:")
    print(classification_report(y_true, y_pred))

    print("Summary Metrics:")
    print(f"Accuracy : {accuracy_score(y_true, y_pred):.4f}")
    print(
        f"Precision: {precision_score(y_true, y_pred, average='weighted'):.4f}")
    print(f"Recall   : {recall_score(y_true, y_pred, average='weighted'):.4f}")
    print(f"F1-score : {f1_score(y_true, y_pred, average='weighted'):.4f}")
    print("\n")


# %%
metrics_horizontal = evaluate(y_test, rf_horizontal.predict(
    X_test), title="Random Forest - Horizontal Partitioning")
metrics_vertical = evaluate(y_test, rf_vertical.predict(
    X_test), title="Random Forest - Vertical Partitioning")
metrics_both = evaluate(y_test, rf_both.predict(
    X_test), title="Random Forest - Combined Partitioning")
metrics = evaluate(y_test, rf.predict(X_test), title="Random Forest")

# %%