# -*- coding: utf-8 -*-
"""lab_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkIfGax5wmEjXqNUZD6umeA075zz_6By
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 

file = pd.read_csv("Fish.csv")
X = file.iloc[:,2:].values
X = np.c_[X, X**2]
Y = file.iloc[:,1].values ## I.M.P ... " :1 -- Creates a 2-D ARRAY .. it's waste for us .. "

# np.random.seed(42)
# indicies = np.random.permutation(len(X))

# X = X[indicies]
# Y = Y[indicies]
# X_mean = np.mean(X, axis=0)
# X_std = np.std(X, axis=0)
# X = (X - X_mean) / X_std

# X_train = X[:100]
# Y_train = Y[:100]
# # ----
# X_val = X[100:130]
# Y_val = Y[100:130]
# #-----------
# X_test = X[130:159]
# Y_test = Y[130:159]

# polynomial features
X = np.c_[X, X**2]

# train / val / test split
X_train, X_temp, Y_train, y_temp = train_test_split(
    X, Y, test_size=0.37, random_state=42, shuffle=True
)

X_val, X_test, Y_val, Y_test = train_test_split(
    X_temp, y_temp, test_size=29/59, random_state=42, shuffle=True
)

# standardization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val   = scaler.transform(X_val)
X_test  = scaler.transform(X_test)
# Y_train = Y_train.ravel()

# 1- ANS :: PLooting graphs .. Extracting column names from data_set
feature_names = file.columns[2:]
for i in range(5) :
  plt.scatter(X_train[:,i],Y_train)
  plt.xlabel(feature_names[i])
  plt.ylabel("weight")
  plt.title(f"WEIGHT (vs) {feature_names[i]}")
  plt.show()

X_train = np.c_[np.ones((X_train.shape[0],1)),X_train]
X_val = np.c_[np.ones((X_val.shape[0],1)),X_val]
X_test = np.c_[np.ones((X_test.shape[0],1)),X_test]

Y_train = Y_train.reshape(-1,1)
Y_val = Y_val.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

def compute_cost(X,Y,teta) :
  m = Y.shape[0]
  Y_pred = np.dot(X,teta) # X.dot(teta) - Also can be used ..
  # cost = ( (1/2) * m)*np.sum( ( Y_pred-Y) **2 ) # MSE
  cost = (1 / (2 * m)) * np.sum((Y_pred - Y) ** 2)
  return cost

def gradient_descent(X,Y,teta,learning_rate,iterations) :
  m = X.shape[0]
  cost_list = []
  for i in range(iterations):
    Y_pred = X.dot(teta)
    d_teta = (1/m) * (np.dot( X.T , Y_pred - Y ) )
    # cost_list.append(compute_cost(X,Y,teta))
    cost = compute_cost(X, Y, teta)
    cost_list.append(cost)
    if i > 1 and abs(cost_list[-2] - cost_list[-1]) < 1e-6:
        break
    teta = teta - (learning_rate) * (d_teta)
  return teta,cost_list

learning_rate = float(input("Enter the Learning-Rate Value :: "))
m = X_train.shape[1] # no.of.features after adding BAIS itslef TO X_TARin..
teta_init = np.zeros((m,1))
iterations = 1000
teta,cost_list = gradient_descent(X_train,Y_train,teta_init,learning_rate,iterations)

#2 TRAIN-ERROR (VS) TEST-ERROR ..
train_mse = compute_cost(X_train,Y_train,teta)
test_mse = compute_cost(X_test,Y_test,teta)
print(f"Avg. MSE for train-set is - {2*train_mse}")
print(f"Avg. MSE for test-set is - {2*test_mse}")
print(f"OPTIMAL-Param . Theta values are :: {teta}")

# 3  - M.S.E  (VS) ITERATIONS ..
plt.plot(cost_list)
plt.xlabel("Iterations")
plt.ylabel("Training_error (MSE)")
plt.title("No.of.Iterations (vs) MSE")
plt.show()

w1_vals = np.linspace(-5, 5, 100)
w2_vals = np.linspace(-5, 5, 100)

loss_surface = np.zeros((len(w1_vals), len(w2_vals)))

for i, w1 in enumerate(w1_vals):
    for j, w2 in enumerate(w2_vals):
        temp_theta = teta.copy()
        temp_theta[1] = w1   # w1 for X1
        temp_theta[2] = w2   # w2 for X2

        loss_surface[i, j] = compute_cost(
            X_train, Y_train, temp_theta
        )

# Contour plot
plt.contour(w1_vals, w2_vals, loss_surface)
plt.xlabel("w1")
plt.ylabel("w2")
plt.title("Loss Surface for (w1, w2)")
plt.show()

initial_thetas = {
    "Zero Init": np.zeros((X_train.shape[1], 1)),
    "One Init":  np.ones((X_train.shape[1], 1)),
    "Random Init": np.random.randn(X_train.shape[1], 1)
}

results = {}

for name, t0 in initial_thetas.items():
    t_final, cost_hist = gradient_descent(
        X_train, Y_train, t0, learning_rate, iterations
    )

    results[name] = {
        "theta": t_final,
        "final_cost": cost_hist[-1]
    }

    plt.plot(cost_hist, label=name)

plt.xlabel("Iterations")
plt.ylabel("Training MSE")
plt.title("Convergence for Different Initial Thetas")
plt.legend()
plt.show()

print("\nComparison of final results:")
for name, res in results.items():
    print(name)
    print("Final MSE:", res["final_cost"])
    print("Final theta:\n", res["theta"])
    print("-" * 30)

# Finding the Optimal-paramters USING HPER-PARAMTER TUNING ...
learn_rates = [0.05,0.08,0.09,0.0999]
best_learning_rate_val= None
best_min_error = float("inf")
for lr in learn_rates :
  temp_teta,_ = gradient_descent(X_train,Y_train,teta_init,lr,iterations)
  val_error = compute_cost(X_val,Y_val,temp_teta)
  print(f"FOR This Learning-Rate - {lr} ; the M.S.E was {val_error}")
  if val_error < best_min_error :
    best_min_error = val_error
    best_learning_rate_val = lr

print(f"Finally the best learning-rate which gives min-error was :: {best_learning_rate_val}")

# before hyper-tuning .. and after Hyper-tuning M.S.E WAS TEST-SET WAS ..
alpha = 0.00065
before_teta,_ = gradient_descent(X_train,Y_train,teta_init,alpha,iterations)
test_mse_init = compute_cost(X_test,Y_test,before_teta)
best_teta,_= gradient_descent(X_train,Y_train,teta_init,best_learning_rate_val,iterations)
test_mse_tuned = compute_cost(X_test,Y_test,best_teta)
print(f"Before Hyper-parameter Tuning with alpha = {alpha} :: M.S.E WAS - {test_mse_init}")
print(f"After Hyper-parameter Tuning with alpha = {best_learning_rate_val} :: M.S.E WAS -  {test_mse_tuned}")